### ISSUE TITLE
Code with nice workflow?

### ISSUE THREAD

**Issue by ctaggart** [TypeStrong/tscs#1]
Where do I find this? I've cloned this repo?

> @ctaggart you might want to clone : https://github.com/TypeStrong/tscs as I did some stuff to play around with the new compiler API with a nice workflow

https://github.com/Microsoft/TypeScript/issues/1615#issuecomment-69118825

**Comment by basarat** [comment]
@ctaggart Just run `grunt`. Sorry for the late reply. Would be great if you AtMention me since the queue is quite big for me otherwise.
